AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'spec/spec_helper.rb'
    - 'config/initializers/assets.rb'
    - 'lib/tasks/cucumber.rake'
    - 'features/support/env.rb'
    - 'custom_plan.rb'
    - 'tmp/**/*'
    - 'bin/*'
    - 'config/*'
    - 'config/initializers/*'
    - 'config/environments/*.rb'
    - 'Gemfile'

Style/ClassAndModuleChildren:
  Enabled: false

Style/RaiseArgs:
  Exclude:
    - 'app/controllers/application_controller.rb'


Metrics/LineLength:
  Max: 200
  Exclude:
    - 'db/seeds/*'
    - 'config/initializers/devise.rb'

Metrics/AbcSize:
  Max: 30
  Exclude:
    - 'app/models/application_record.rb'

Lint/ShadowingOuterLocalVariable:
  Exclude:
    - 'app/models/application_record.rb'


Documentation:
  Enabled: false

CaseIndentation:
  Enabled: false
